### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by caffo** [mlava/focus-mode#2]
I installed it through roam depot and can't find the command in the palette:

<img width="1055" alt="CleanShot 2023-03-12 at 11 37 52@2x" src="https://user-images.githubusercontent.com/456/224565300-657cb316-87b1-408f-bba0-b01d80ce5598.png">

<img width="670" alt="CleanShot 2023-03-12 at 11 38 33@2x" src="https://user-images.githubusercontent.com/456/224565319-cbfae554-3479-4751-b282-519885ecbb30.png">

**Comment by mlava** [comment]
Hi there. Could you check which version you have? 
![Screenshot_20230313-081421](https://user-images.githubusercontent.com/6857790/224574158-0cf65d8d-0a7e-400b-a870-b19f83d74a42.png)

**Comment by caffo** [comment]
<img width="469" alt="CleanShot 2023-03-12 at 15 48 19@2x" src="https://user-images.githubusercontent.com/456/224578593-dcad5d85-cf0d-47b0-a6f6-13076adb660a.png">

**Comment by mlava** [comment]
Thanks.
Is this on mobile or browser/desktop?
Electron (installed) vs browser?
If you're in browser, could you please open console (F12), clear it, then disable and re-enable the extension. If there are errors in console, please post them here.

**Comment by caffo** [comment]
I found the issue -- it's not your extension fault. I'm using an old and low-spec mac laptop, so instead of using the electron app I decide to use this to create the packaged app: https://github.com/kofigumbs/multi.

For some reason, the extension works on my browser but not on my multi-based Roam. app -- I will debug this. Thanks!
